[workspace]
resolver = "2"
members = ["core", "daemon"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
authors = ["Shagov Alexei <shagov.alexei@gmail.com>"]
repository = "https://github.com/shagovAlexei/cosmic-ext-lang-switch"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
zbus = { version = "5", default-features = false, features = ["tokio"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }
log = "0.4"
simple_logger = "5"
cosmic-config = { git = "https://github.com/pop-os/libcosmic", rev = "ef490df50b0a05a21c494c3f75737581bf0b39d9", default-features = false, features = ["macro"] }
