[package]
name = "cosmic-ext-lang-switch"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
lsc = { package = "cosmic-ext-lang-switch-core", path = "../core" }
zbus.workspace = true
tokio.workspace = true
log.workspace = true
simple_logger.workspace = true
i18n-embed = { version = "0.16", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.10"
rust-embed = "8"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = ["applet", "tokio", "wayland", "winit", "process", "single-instance", "about"]
